### ISSUE TITLE
Requiring some ;features

### ISSUE THREAD

**Issue by Pyh2002** [linsyking/CanvasHelper#2]
1. Add limiting the number of information for ass/dis
2. Show the week number(for example, Week 6) on the right of annoucement

**Comment by linsyking** [comment]
1. Done
2. Can you show me how to find the week number in your canvas system? I can't find it? Or do you want to set the start date of the semester in the `user_data.json` file?

**Comment by linsyking** [comment]
Fixed, please update to the newest version.
