### ISSUE TITLE
读不到canvas里没有时间限制的assignments

### ISSUE THREAD

**Issue by ghost** [linsyking/CanvasHelper#3]
如题，有的老师他不在canvas里设置ddl，结果桌面显示里就只能读到有ddl的作业，那些没设置ddl的就不显示了

**Comment by linsyking** [comment]
我默认配置的是只显示有ddl的作业，否则太多了。我之后加个自定义选项吧，改好了通知你

**Comment by linsyking** [comment]
> 如题，有的老师他不在canvas里设置ddl，结果桌面显示里就只能读到有ddl的作业，那些没设置ddl的就不显示了

已修复，不需要改配置。如果没有查到ddl默认使用最后更改日期。因为我这边没有这样的课程，麻烦你看一下有没有解决问题，谢谢。
