### ISSUE TITLE
桌面不显示窗口

### ISSUE THREAD

**Issue by dscmarkw** [linsyking/CanvasHelper#8]
如题，之前都可以正常使用，但是从昨天开始，开机后桌面就不出现提醒窗口了。
在Wallpaper Engine内重置后出现窗口，提醒需要选择文件夹；选择文件夹后则显示"Please Check your Internet Connection."
确定网络可用（否则也没法发这个issue）。本人非密院，使用oc.sjtu.edu.cn的canvas系统。
烦请大佬排查一下，谢谢。

**Comment by linsyking** [comment]
现在应该好了？

**Comment by dscmarkw** [comment]
解决了，感谢大佬
